# Coursera Spacecraft Dynamics and Control - Kinematics
## Module 3
## Concept Check 18 - MRP to DCM Relation

In [1]:
import numpy as np
import sys

sys.path.append('../')

import attitude_math as am

### Question 1
Map σ=(0.1,0.2,0.3) to the corresponding DCM

In [2]:
dcm = am.MRP_2_DCM([0.1, 0.2, 0.3])
print(dcm)
print(dcm.reshape(9).tolist())

[[ 0.19975377  0.91720529 -0.34472145]
 [-0.67097568  0.38442598  0.63404124]
 [ 0.71406587  0.10464758  0.69221299]]
[0.19975377039088948, 0.9172052939365958, -0.3447214527546937, -0.6709756848261001, 0.3844259772237611, 0.634041243459526, 0.714065866420437, 0.1046475838719606, 0.6922129886118804]


### Question 2
Map the DCM

\begin{bmatrix}
0.763314 & 0.0946746 & -0.639053 \\
-0.568047 & -0.372781 & -0.733728 \\
-0.307692 & 0.923077 & -0.230769 \\
\end{bmatrix}

to the equivalent short MRP set.


In [3]:
dcm = np.array([[0.763314, 0.0946746, -0.639053],
                [-0.568047, -0.372781, -0.733728],
                [-0.307692, 0.923077, -0.230769]])
mrp = am.DCM_2_MRP(dcm)
print(mrp)

[-0.49999996  0.0999997   0.19999992]
