# Coursera Spacecraft Dynamics and Control - Kinematics
## Module 3
## Concept Check 5,6 - Euler Parameter Relationship to DCM

In [10]:
import numpy as np
import math
import sys
sys.path.append('../')

import attitude_math as am

### Problem 1
Question 1
Given $\beta = (0.235702, 0.471405, -0.471405, 0.707107)$, what is the corresponding DCM?

In [11]:
def result():
    q = [0.235702,0.471405,-0.471405,0.707107]
    dcm = am.quat_2_dcm(q)
    return dcm

r = np.array(result()).reshape(3,3)
print(r)
np.linalg.det(r)

[[-0.44444488 -0.11111228  0.88888975]
 [-0.77777842 -0.44444488 -0.44444535]
 [ 0.44444535 -0.88888975  0.11111039]]


1.0000032709125666

### Problem 3

Write a program to map a DCM to the equivalent EP.  Choose the EP output set that describes a short rotation.  Using 
$$\begin{bmatrix}
B \\
N
\end{bmatrix}
=
\begin{bmatrix}
-0.529403 & -0.467056 & 0.708231 \\
-0.474115 & -0.529403 & -0.703525 \\
0.703525 & -0.708231 & 0.0588291 \\
\end{bmatrix}
\```$$​
  

what is the corresponding EP set?

In [12]:

# adjust the return matrix values as needed
def result():
    r = [[-0.529403, -0.467056,  0.708231],
         [-0.474115, -0.529403, -0.703525],
         [ 0.703525, -0.708231, 0.0588291]]
    ep = am.dcm_2_quat(r)
    return ep

r = result()
print(r)
np.linalg.norm(r)

[0.002403122968142373, 0.4850698145628112, -0.4850698145628112, 0.7276048206272413]


1.0

### Problem 4

Given the 3-2-1 Euler Angles set (20,10,-10) degrees, what is the equivalent EP set?

In [13]:
# adjust the return matrix values as needed
def result():
    r=am.eulerAd([3,2,1],[20,10,-10])
    eulerParameters=am.dcm_2_quat(r)
    return eulerParameters
    
r = result()
print(r)
np.linalg.norm(r)


[0.9760079787005331, -0.10058188063494031, 0.07042819102789467, 0.17980984597450927]


1.0