# Coursera Spacecraft Dynamics and Control - Kinetics
## Module 1


In [10]:
import numpy as np
import sys
sys.path.append("../../")

import attitude_math as am

## Concept Check 5 - Rigid Body Angular Momentum
### Question 4
A spacecraft has an orientation expressed through (3-2-1) Euler angles as $(-10, 10,5)$ degrees. A body angular velocity is $\mathbf{^N\omega}=(0.01,-0.01,0.01)$ rad/sec. The inertia tensor is expressed in body frame components as $\mathbf{^B[I]}=\begin{bmatrix} 10 & 1 & -1 \\
1 & 5 & -1 \\
1 & 1 & 8 \end{bmatrix}$. What is the spacecraft angular momentum in body frame components?

In [11]:
omega = np.array([0.01, -0.01, 0.01])
R = am.eulerAd([3,2,1],[-10,10,5])
I = np.array([[10, 1, -1],
              [1, 5, 1],
              [-1, 1, 8]])

H = I@(R@omega)
print(H.tolist())

[0.07715217653936335, -0.013041792460218806, 0.08345329154684628]


## Concept Check 6 - Parallel Axis Theorem
### Question 1
A spacecraft with mass 12.5kg has an orientation expressed through (3-2-1) Euler angles as $(-10, 10,5)$ degrees. The spacecraft inertia tensor about the center of mass location is expressed as

$\mathbf{^B[I_c]}=\begin{bmatrix} 10 & 1 & -1 \\ 1 & 5 &
1 \\ -1 & 1 & 8 \end{bmatrix}$

What is the inertia about point P  where $\mathbf{^N R_{c/P}}=(-0.5,0.5,0.25)$ meters. Express your inertia tensor again in $\mathbf{B}$-frame components.


In [14]:
rN_CP = np.array([-.5,.5,.25])
rB_cp = R@rN_CP
M = 12.5
I_P = I + 12.5*am.tilde(rB_cp)@am.tilde(rB_cp).transpose()
print(I_P.reshape(9).tolist())

[12.321252066866062, 4.197555618660198, -0.15813866771502283, 4.197555618660198, 9.860471566638285, 0.4284714194365996, -0.15813866771502283, 0.4284714194365996, 14.88077636649565]


## Concept Check 6.1 - Coordinate Transformation
### Question 1
The spacecraft inertia tensor about the center of mass location is expressed as

$\mathbf{^B[I_c]}=\begin{bmatrix} 10 & 1 & -1 \\ 1 & 5 & 1 \\ -1 & 1 & 8 \end{bmatrix}$

What is the inertia tensor expressed in terms of body docking frame D components where the D orientation relative to B is given through the MRPs $\sigma_{D/B}=(0.1, 0.2, 0.3)$?


In [16]:
mrp = [.1,.2,.3]
R = am.MRP_2_DCM(mrp)
I_d = R@I@R.transpose()
print(I_d.reshape(9).tolist())

[5.427795052311948, -1.7734101199876724, 1.3798823058088003, -1.7734101199876726, 9.279522141007751, -0.5304735192806451, 1.3798823058088006, -0.530473519280645, 8.292682806680293]


### Question 2
The spacecraft inertia tensor about the center of mass location is expressed as $\mathbf{^B[I_c]}=\begin{bmatrix} 10 & 1 & -1 \\ 1 & 5 & 1 \\ -1 & 1 & 8 \end{bmatrix}$. What are the principal inertias? Provide the principal inertias ranked by size with the largest principal inertia first.

### Question 4
Which frame F orientation results in a principal coordinate frame?  Order the principal inertias by size with the largest principal inertia being along the first base vector 
$\hat{𝑓}_1$, etc.

In [46]:
lamb,v = np.linalg.eig(I)
print(f"Principal moments: {lamb}\nEigen vectors:\n{v}")
i = np.argsort(lamb)[-1::-1]
v[:,1]=-v[:,1]
print(f"Principal moments: {lamb[i]}\nRotation Matrix:\n{v[:,i].transpose().reshape(9).tolist()}")
np.linalg.det(v[:,i].transpose())

Principal moments: [ 4.41312549 10.47419366  8.11268085]
Eigen vectors:
[[ 0.22199371 -0.93616416  0.27260861]
 [-0.92146211 -0.11001782  0.37256363]
 [ 0.31878891  0.33390528  0.88706307]]
Principal moments: [10.47419366  8.11268085  4.41312549]
Rotation Matrix:
[0.9361641624967313, 0.11001782461409362, -0.33390528466015057, 0.27260860554517957, 0.37256362930852255, 0.8870630700796727, 0.22199371396394596, -0.9214621101182862, 0.31878891225519307]


0.9999999999999998

## Concept Check 7 - Kinetic Energy

### Question 1
The spacecraft inertia tensor about the center of mass location is expressed as $\mathbf{^B[I_c]}=\begin{bmatrix} 10 & 1 & -1 \\ 1 & 5 & 1 \\ -1 & 1 & 8 \end{bmatrix}$. The body angular velocity is given by $\mathbf{^B\omega}=(0.01,-0.01,0.01)$ rad/s. What is the rotational kinetic energy?

In [50]:
omega = np.array([0.01, -.01, .01])
RKE = 1/2*omega@I@omega
print(f"Rotational Kinetic Energy:\n{RKE}")

Rotational Kinetic Energy:
0.0008500000000000001
