# Coursera Spacecraft Dynamics and Control - Capstone Mars Misson
## Module 3

In [5]:
import numpy as np
import sys
sys.path.append("../")
sys.path.append("../..")

import Sat_Orbits as SO
import attitude_math as am

## Programming Assignment: Task 3: Sun-Pointing Reference Frame Orientation
To point the spacecraft solar panels axis $b_3$ at the sun, the reference frame $R_s$ must be chosen such that $r_3$ axis points in the sun direction ($n_2$ in this scenario). Further, assume the first axis $r_1$ points in the $n_1$ direction. Your tasks are:

1. Determine an analytic expression for the sun pointing reference frame $R_s$ by defining the direction cosine matrix $[R_sN]$.
2. Write a function that returns $[R_sN]$.
3. Validate the evaluation of $[R_sN]$ by providing the numerical values for $t = 0s$.
4. What is the angular velocity $N$ of $R_sN$?

Your tasks are:

1. Determine an analytic expressions for the sun pointing reference frame \(R_s\) by defining the DCM \([R_sN]\).

2. Write a function that returns \([R_sN]\).

Then submit the following tasks for grading in Coursera:

Part 1: Validate the evaluation of \([R_sN]\) by providing the numerical values for \(t = 0\)s. List these values in a plain text file with spaces between each number as "a b c".

Tolerance +/- 0.001

Part 2: What is the angular velocity \(N\omega_{Rs/N}\)? List the values in your result in a plain text file with spaces between each number as "a b c".

Tolerance +/- \(10^{-7}\)

*Answer* 

Since the sun reference frame is fixed to the inertial frame for the purposes of this we will define a DCM to go from N to $R_s$ and then transpose. To do this we will first rotate about N1 90 degrees to get N2 to align to R3. The we will rotate 180 degrees about the new N2 (aka R3) vector to get -N1 to align with R1 since N1 is still in place but we want it to be -180 out of alignment. I will use my euler angle functions to get this matrix.

It is also not rotating so the angular velocity is zero

In [6]:
R_RsN = am.eulerAd([1,2],[90,180])
print(f"R_RsN = {R_RsN}")
with open("SCDC-M3-T3-P1.txt","w") as f:
    f.write(" ".join(str(num) for num in R_RsN.reshape(9)))
print(f"Test N2 rotation to R3: {R_RsN.transpose()@[0,1,0]}")
print(f"Test N1 rotation to -R1: {R_RsN.transpose()@[1,0,0]}")

omega_RsN = np.zeros(3)
with open("SCDC-M3-T3-P2.txt","w") as f:
    f.write(" ".join(str(num) for num in omega_RsN))

R_RsN = [[-1.00000000e+00  1.22464680e-16 -7.49879891e-33]
 [ 0.00000000e+00  6.12323400e-17  1.00000000e+00]
 [ 1.22464680e-16  1.00000000e+00 -6.12323400e-17]]
Test N2 rotation to R3: [0.000000e+00 6.123234e-17 1.000000e+00]
Test N1 rotation to -R1: [-1.00000000e+00  1.22464680e-16 -7.49879891e-33]


## Task 4: Nadir-Pointing Reference Frame Orientation

To point the spacecraft sensor platform axis $b_1$ towards the center of Mars or nadir direction, the reference frame $R_n$ must be chosen such that $r_1$ axis points towards the planet. Further, assume the second axis $r_2$ points in the velocity direction. Your tasks are:

1. Determine an analytic expression for the nadir pointing reference frame $R_n$ by defining the DCM $[R_nN]$.
2. Write a function that returns $[R_nN]$ as a function of time.
3. Write a function that determines the angular velocity vector $N_{R_nN}$.
4. Validate the evaluation of $[R_nN]$ by providing the numerical values for $t = 330s$.
5. What is the angular velocity $N_{R_nN}(330s)$?



Your tasks are:
- Determine an analytic expression for the nadir pointing reference frame $R_n$ by defining the DCM $[R_nN]$.

- Write a function that returns $[R_nN]$ as a function of time.

- Write a function that determines the angular velocity vector $N_{R_nN}$.

Then submit the following tasks for grading in Coursera:

Part 1: Validate the evaluation of $[R_nN]$ by providing the numerical values for $t = 330s$. List these values in a plain text file with spaces between each number as "a b c".

Tolerance +/- 0.001

Part 2: What is the angular velocity $N_{R_nN}(330s)$? List the values in your result in a plain text file with spaces between each number as "a b c".

Tolerance +/- 0.001


In [7]:
# Nadir can be define in reference to Hill frame
R_RnH = am.eulerAd([2],[180])
print(f"R_RnH: {R_RnH}")

r_n1 = R_RnH.transpose() @ [1,0,0]
print(f"r_n1: {r_n1}")
r_n2 = R_RnH.transpose() @ [0,1,0]
print(f"r_n2: {r_n2}")

t=330
#R_RnN = R_RnH@SO.LMO_sat.R_HN(t)
R_RnN = SO.LMO_sat.R_RnN(t)
with open("SCDC-M3-T4-P1.txt","w") as f:
    f.write(" ".join(str(num) for num in R_RnN.reshape(9)))

# Since Nadir is locked to the hilbert frame their omegas in the 
# N frame are the same
#omega_RnN_N = SO.LMO_sat.R_HN(t).transpose() @ SO.LMO_sat.omega_H_h
omega_RnN_N = SO.LMO_sat.omega_RnN_N(t)
with open("SCDC-M3-T4-P2.txt","w") as f:
    f.write(" ".join(str(num) for num in omega_RnN_N))

print(f"Omega_RnN_N: {omega_RnN_N}")

R_RnH: [[-1.0000000e+00  0.0000000e+00 -1.2246468e-16]
 [ 0.0000000e+00  1.0000000e+00  0.0000000e+00]
 [ 1.2246468e-16  0.0000000e+00 -1.0000000e+00]]
r_n1: [-1.0000000e+00  0.0000000e+00 -1.2246468e-16]
r_n2: [0. 1. 0.]
Omega_RnN_N: [ 0.00015131 -0.00041572  0.00076626]


## Task 5: GMO-Pointing Reference Frame Orientation (10 points)

To point the nano-satellite communication platform axis $b_1$ towards the GMO mother spacecraft, the communication reference frame $R_c$ must be chosen such that $r_1$ axis points towards the GMO satellite location. Assume $r = r_{GMO} \cdot r_{LMO}$. Further, to fully define a three-dimensional reference frame, assume the second axis is defined as $r_2 = \frac{\Delta r \times n_3}{|\Delta r \times n_3|}$, while the third is then defined as $r_3 = r_1 \times r_2$. 

Your tasks are:
1. Determine an analytic expression for the communication mode reference frame $R_c$ by defining the direction cosine matrix $[R_cN]$.
2. Write a function that returns $[R_cN]$ as a function of time.
3. Write a function that determines the angular velocity vector $N_{R_cN}$. Note that an analytical expression for this body rate vector is very challenging. It is okay to use numerical differences in these frames to compute $\frac{d[R_cN]}{dt}$, and then relate this to $R_cN$. As the orbit trajectories are given as a function of time, it is straightforward to include a time-based numerical difference method.
4. Validate the evaluation of $[R_cN]$ by providing the numerical values for $t = 330s$.
5. Validate the angular velocity $N_{R_cN}(330s)$.

Your tasks are:

Determine an analytic expression for the communication mode reference frame $R_cN$ by defining the DCM $[R_cN]$.

Write a function that returns $[R_cN]$ as a function of time.

Write a function that determines the angular velocity vector $\omega_{Rc/N}$. Note that an analytical expression for this body rate vector is very challenging. It is okay to use numerical differences in these frames to compute $\frac{d[R_cN]}{dt}$, and then relate this to $\omega_{Rc/N}$. As the orbit trajectories are given as a function of time, it is straightforward to include a time-based numerical difference method.

Then submit the following tasks for grading in Coursera:

Part 1: Validate the evaluation of $[R_cN]$ by providing the numerical values for $t=330$ s. List these values in a plain text file with spaces between each number as "a b c". Tolerance: $\pm 0.001$.

Part 2: Validate the angular velocity $\omega_{Rc/N}(330 \text{ s})$. List the values in a plain text file with spaces between each number as "a b c". Tolerance: $\pm 10^{-7}$.


In [11]:
# Create a function to build a DCM from component vectors
def Get_Comm_Frame_DCM(t):
    delta_r_N = SO.GMO_sat.inertial_state(t)[0] - SO.LMO_sat.inertial_state(t)[0]
    r1 = -delta_r_N/np.linalg.norm(delta_r_N)
    r2 = np.cross(delta_r_N, [0,0,1])
    r2 = r2/np.linalg.norm(r2)
    r3 = np.cross(r1,r2)
    R_RcN = np.vstack([r1,r2,r3])
    return R_RcN

def Get_Comm_Frame_Inertial_Rate(t1,t0):
    dcm1 = Get_Comm_Frame_DCM(t1)
    dcm0 = Get_Comm_Frame_DCM(t0)
    omega = am.dcmdot_2_oemga(dcm1,dcm0,t1-t0)
    omega_RcN_N = dcm1.transpose()@omega
    return omega_RcN_N

    

R_RcN = Get_Comm_Frame_DCM(330)
print(f"R_RcN: {R_RcN}")
with open("SCDC-M3-T5-P1.txt","w") as f:
    f.write(" ".join(str(num) for num in R_RcN.reshape(9)))

omega_RcN_N = Get_Comm_Frame_Inertial_Rate(330,329.999)
print(f"Omega_RcN: {omega_RcN_N}")
with open("SCDC-M3-T5-P2.txt","w") as f:
    f.write(" ".join(str(num) for num in omega_RcN_N))

R_RcN: [[ 0.26547539  0.96092816  0.07835742]
 [-0.96389181  0.26629415  0.        ]
 [-0.02086612 -0.07552807  0.99692533]]
Omega_RcN: [ 1.97829434e-05 -5.46543293e-06  1.91300024e-04]
