# Coursera Spacecraft Dynamics and Control - Capstone Mars Misson
## Module 3

In [1]:
import numpy as np
import sys
sys.path.append("../")
sys.path.append("../..")

import Sat_Orbits as SO
import attitude_math as am

## Programming Assignment: Task 3: Sun-Pointing Reference Frame Orientation
To point the spacecraft solar panels axis $b_3$ at the sun, the reference frame $R_s$ must be chosen such that $r_3$ axis points in the sun direction ($n_2$ in this scenario). Further, assume the first axis $r_1$ points in the $n_1$ direction. Your tasks are:

1. Determine an analytic expression for the sun pointing reference frame $R_s$ by defining the direction cosine matrix $[R_sN]$.
2. Write a function that returns $[R_sN]$.
3. Validate the evaluation of $[R_sN]$ by providing the numerical values for $t = 0s$.
4. What is the angular velocity $N$ of $R_sN$?

Your tasks are:

1. Determine an analytic expressions for the sun pointing reference frame \(R_s\) by defining the DCM \([R_sN]\).

2. Write a function that returns \([R_sN]\).

Then submit the following tasks for grading in Coursera:

Part 1: Validate the evaluation of \([R_sN]\) by providing the numerical values for \(t = 0\)s. List these values in a plain text file with spaces between each number as "a b c".

Tolerance +/- 0.001

Part 2: What is the angular velocity \(N\omega_{Rs/N}\)? List the values in your result in a plain text file with spaces between each number as "a b c".

Tolerance +/- \(10^{-7}\)

*Answer* 

Since the sun reference frame is fixed to the inertial frame for the purposes of this we will define a DCM to go from N to $R_s$ and then transpose. To do this we will first rotate about N1 90 degrees to get N2 to align to R3. The we will rotate 180 degrees about the new N2 (aka R3) vector to get -N1 to align with R1 since N1 is still in place but we want it to be -180 out of alignment. I will use my euler angle functions to get this matrix.

It is also not rotating so the angular velocity is zero

In [2]:
R_RsN = am.eulerAd([1,2],[90,180])
print(f"R_RsN = {R_RsN}")
with open("SCDC-M3-T3-P1.txt","w") as f:
    f.write(" ".join(str(num) for num in R_RsN.reshape(9)))
print(f"Test N2 rotation to R3: {R_RsN.transpose()@[0,1,0]}")
print(f"Test N1 rotation to -R1: {R_RsN.transpose()@[1,0,0]}")

omega_RsN = np.zeros(3)
with open("SCDC-M3-T3-P2.txt","w") as f:
    f.write(" ".join(str(num) for num in omega_RsN))

R_RsN = [[-1.00000000e+00  1.22464680e-16 -7.49879891e-33]
 [ 0.00000000e+00  6.12323400e-17  1.00000000e+00]
 [ 1.22464680e-16  1.00000000e+00 -6.12323400e-17]]
Test N2 rotation to R3: [0.000000e+00 6.123234e-17 1.000000e+00]
Test N1 rotation to -R1: [-1.00000000e+00  1.22464680e-16 -7.49879891e-33]


## Task 4: Nadir-Pointing Reference Frame Orientation

To point the spacecraft sensor platform axis $b_1$ towards the center of Mars or nadir direction, the reference frame $R_n$ must be chosen such that $r_1$ axis points towards the planet. Further, assume the second axis $r_2$ points in the velocity direction. Your tasks are:

1. Determine an analytic expression for the nadir pointing reference frame $R_n$ by defining the DCM $[R_nN]$.
2. Write a function that returns $[R_nN]$ as a function of time.
3. Write a function that determines the angular velocity vector $N_{R_nN}$.
4. Validate the evaluation of $[R_nN]$ by providing the numerical values for $t = 330s$.
5. What is the angular velocity $N_{R_nN}(330s)$?



Your tasks are:
- Determine an analytic expression for the nadir pointing reference frame $R_n$ by defining the DCM $[R_nN]$.

- Write a function that returns $[R_nN]$ as a function of time.

- Write a function that determines the angular velocity vector $N_{R_nN}$.

Then submit the following tasks for grading in Coursera:

Part 1: Validate the evaluation of $[R_nN]$ by providing the numerical values for $t = 330s$. List these values in a plain text file with spaces between each number as "a b c".

Tolerance +/- 0.001

Part 2: What is the angular velocity $N_{R_nN}(330s)$? List the values in your result in a plain text file with spaces between each number as "a b c".

Tolerance +/- 0.001


In [6]:
# Nadir can be define in reference to Hill frame
R_RnH = am.eulerAd([2],[180])
print(f"R_RnH: {R_RnH}")

r_n1 = R_RnH.transpose() @ [1,0,0]
print(f"r_n1: {r_n1}")
r_n2 = R_RnH.transpose() @ [0,1,0]
print(f"r_n2: {r_n2}")

t=330
R_RnN = R_RnH@SO.LMO_sat.R_HN(t)
with open("SCDC-M3-T4-P1.txt","w") as f:
    f.write(" ".join(str(num) for num in R_RnN.reshape(9)))

# Since Nadir is locked to the hilbert frame their omegas in the 
# N frame are the same
omega_RnN_N = SO.LMO_sat.R_HN(t).transpose() @ SO.LMO_sat.omega_H_h
with open("SCDC-M3-T4-P2.txt","w") as f:
    f.write(" ".join(str(num) for num in omega_RnN_N))
print(omega_RnN_N)

R_RnH: [[-1.0000000e+00  0.0000000e+00 -1.2246468e-16]
 [ 0.0000000e+00  1.0000000e+00  0.0000000e+00]
 [ 1.2246468e-16  0.0000000e+00 -1.0000000e+00]]
r_n1: [-1.0000000e+00  0.0000000e+00 -1.2246468e-16]
r_n2: [0. 1. 0.]
[ 0.00015131 -0.00041572  0.00076626]
