# Coursera Spacecraft Dynamics and Control - Capstone Mars Misson
## Module 5

In [1]:
import numpy as np
import sys
from plotly import graph_objects as pgo
sys.path.append("../")
sys.path.append("../..")

import Sat_Orbits as SO
import attitude_math as am

In [2]:
get_state_at_time = lambda df, t: df.loc[df['t'] == t].to_numpy()

## Programming Assignment: Task 8: Sun Pointing Control
First, the individual control pointing modes are developed and tested on their own. Next, they are combined into a full mission scenario simulation in section 4.11. In the current task, use the initial spacecraft attitude and orbit conditions in section 3.1 and Table 2 and assume the spacecraft is to engage directly into a sun-pointing mode starting at $t_0$. The attitude control law is the simple PD control shown in Eq. (4).

Your tasks are:
1. Numerically implement this control law in your earlier simulation and ensure that sun-pointing is achieved with the desired closed-loop performance.
2. Use linearized closed-loop dynamics of a regular problem, such as this sun pointing control, to determine the $K$ and $P$ feedback gains such that the slowest decay response time (i.e., time for tracking errors to be $1/e$ the original size) is 120 seconds. This means all decay time constants should be 120 seconds or less. Further, the closed-loop response for all BN components should be either critically damped or under-damped. Thus, at least one mode must be critically damped with $\zeta=1$, while the other modes will have $\zeta<1$.
3. Validate the response by providing the BN states at $t = 15s$, $t = 100s$, $t = 200s$, and $t = 400s$. Note that you must always provide the MRP corresponding to the short rotation.


Your tasks are:

- Numerically implement this control law in your earlier simulation and ensure that sun-pointing is achieved with the desired closed-loop performance.

- Use linearized closed-loop dynamics of a regular problem, such as this sun pointing control, to determine the feedback gains K and P such that the slowest decay response time (i.e., time for tracking errors to be 1/e the original size) is 120 seconds. This means all decay time constants should be 120 seconds or less. Further, the closed-loop response for all σB/N components should be either critically damped or underdamped. Thus, at least one must be critically damped with ξ = 1, while the other modes will have ξ ≤ 1.

- Validate the response by providing the σB/N states at t = 15s, 100s, 200s, and 400s. Note that you must always provide the MRP corresponding to the short rotation.

Submit the following for grading on Coursera:

### Part 1: 
Submit a plain text file listing first the P feedback gain and then the K feedback gain. Tolerance: ±0.0001.



In [3]:
Iis = SO.LMO_sat.MOI.diagonal()
Ps = 2*Iis/120
print(f"P Candidates: {Ps}")
P = max(Ps)
E_target = 1
K_s = (P/E_target)**2/Iis
print(f"K Candidates: {K_s}")
K = max(K_s)

print(f"Selected Gains\tK = {K},\tP = {P}")
Ts = 2*Iis/P
Eis = P/np.sqrt(K*Iis)
print(f"Time decay constants: {Ts}\nDamping ratio: {Eis}")

with open("SCDC-M3-T8-P1.txt","w") as f:
    f.write(" ".join([str(P), str(K)]))

def linear_control(X, Xr, t):
    if callable(Xr):
        Xr = Xr(t)
    sigma_BR = am.DCM_2_MRP(am.MRP_2_DCM(X[0])@am.MRP_2_DCM(Xr[0]).transpose())
    omega_BR_B = X[1]-Xr[1]
    return - K*sigma_BR - P*omega_BR_B

P Candidates: [0.16666667 0.08333333 0.125     ]
K Candidates: [0.00277778 0.00555556 0.0037037 ]
Selected Gains	K = 0.005555555555555555,	P = 0.16666666666666666
Time decay constants: [120.  60.  90.]
Damping ratio: [0.70710678 1.         0.81649658]


### Part 2-5: Simulation 

In [4]:
SO.LMO_sat.reset_X()
# omega_0 = SO.LMO_sat.X()[1].transpose()
# H=SO.LMO_sat.MOI@omega_0
# print(f"H(0 s) = {H}")

t_step=1
target = np.vstack([SO.MRP_RsN, SO.omega_RsN])
data = SO.orbital_att_RK4int(SO.LMO_sat,
                      lambda x,t: SO.linear_control(x, 
                                                 target,
                                                 t, K, P),
                      np.zeros(3),
                      SO.LMO_sat.X(),
                      np.arange(0,400+t_step,t_step))
print(data)

fig = pgo.Figure()
sigma = target[0]
fig.add_scatter3d(x=data["sigma1"],
                  y=data["sigma2"],
                  z=data["sigma3"],
                  mode="lines")

lastval = data.iloc[-1].to_numpy()
print(lastval)
sigma_BR = am.DCM_2_MRP(am.MRP_2_DCM(lastval[1:4])@am.MRP_2_DCM(target[0]).transpose())
print(sigma_BR)
fig.add_scatter3d(x=[sigma[0]],
                  y=[sigma[1]],
                  z=[sigma[2]],
                  mode="markers")
fig.show()

         t    sigma1    sigma2    sigma3    omega1    omega2    omega3
0      0.0  0.300000 -0.400000  0.500000  0.017453  0.030543 -0.038397
1      1.0  0.298235 -0.381090  0.496846  0.017881  0.030386 -0.037217
2      2.0  0.296351 -0.362695  0.493923  0.018280  0.030237 -0.036049
3      3.0  0.294361 -0.344785  0.491223  0.018651  0.030095 -0.034895
4      4.0  0.292276 -0.327334  0.488737  0.018995  0.029957 -0.033754
..     ...       ...       ...       ...       ...       ...       ...
396  396.0 -0.010877 -0.719551 -0.684502 -0.000832  0.000076 -0.000485
397  397.0 -0.010682 -0.719372 -0.684899 -0.000825  0.000075 -0.000479
398  398.0 -0.010489 -0.719195 -0.685293 -0.000818  0.000074 -0.000473
399  399.0 -0.010299 -0.719018 -0.685682 -0.000811  0.000073 -0.000467
400  400.0 -0.010111 -0.718841 -0.686069 -0.000804  0.000072 -0.000461

[401 rows x 7 columns]
[ 4.00000000e+02 -1.01114031e-02 -7.18841470e-01 -6.86068657e-01
 -8.03911498e-04  7.17871175e-05 -4.61049148e-04]
[ 0.01166

### Part 2:
Submit a plain text file containing the MRP $\sigma_{B/N}$ at t = 15s. 

Tolerance: ±0.001.

In [5]:
sigma_BN = get_state_at_time(data, t=15)[0,1:4]
print(sigma_BN)
with open("SCDC-M3-T8-P2.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

[ 0.26559696 -0.15982902  0.47332779]


### Part 3:
Submit a plain text file containing the MRP $\sigma_{B/N}$ at t = 100s. 

Tolerance: ±0.001.

In [6]:
sigma_BN = get_state_at_time(data, t=100)[0,1:4]
print(sigma_BN)
with open("SCDC-M3-T8-P3.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

[0.16882716 0.54822575 0.57886626]


### Part 4:
Submit a plain text file containing the MRP $\sigma_{B/N}$ at t = 200s. 

Tolerance: ±0.001.

In [7]:
sigma_BN = get_state_at_time(data, t=200)[0,1:4]
print(sigma_BN)
with open("SCDC-M3-T8-P4.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

[-0.11812732 -0.75785989 -0.59149202]


### Part 5:
Submit a plain text file containing the MRP $\sigma_{B/N}$ at t = 400s. 

Tolerance: ±0.001.

In [8]:
sigma_BN = get_state_at_time(data, t=400)[0,1:4]
print(sigma_BN)
with open("SCDC-M3-T8-P5.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

[-0.0101114  -0.71884147 -0.68606866]


## Programming Assignment: Task 9: Nadir Pointing Control (10 points)
Next, the nadir pointing attitude mode is created and tested. Use the same gains K and P as developed for sun-pointing, and the PD control in Eq. (4). Your tasks are:

- Numerically implement the nadir pointing control mode and assume that at t0 nadir pointing is required, even though the satellite is in the sunlight at this time.

- Validate the response by providing the BN states at t = 15s, 100s, 200s, and 400s. Note that you must always provide the MRP corresponding to the short rotation.


In [9]:
SO.LMO_sat.reset_X()
# omega_0 = SO.LMO_sat.X()[1].transpose()
# H=SO.LMO_sat.MOI@omega_0
# print(f"H(0 s) = {H}")

t_step=1
t_f=1200
Xr = lambda t: np.vstack([am.DCM_2_MRP(SO.LMO_sat.R_RnN(t)),
                          SO.LMO_sat.R_BN()@SO.LMO_sat.omega_RnN_N(t)])

control = lambda x, t: SO.linear_control(x, 
                                         Xr,
                                         t, K, P)
data = SO.orbital_att_RK4int(SO.LMO_sat,
                      control,
                      np.zeros(3),
                      SO.LMO_sat.X(),
                      np.arange(0,t_f+t_step,t_step))
print(data)

fig = pgo.Figure()
sigma = np.array([Xr(t).flatten() for t in np.arange(0,t_f+t_step,t_step)])

fig.add_scatter3d(x=sigma[:,0],
                  y=sigma[:,1],
                  z=sigma[:,2],
                  mode="markers",
                  marker={"size": 1})
fig.add_scatter3d(x=data["sigma1"],
                  y=data["sigma2"],
                  z=data["sigma3"],
                  marker={"size": 1})
fig.show()

           t    sigma1    sigma2    sigma3        omega1        omega2  \
0        0.0  0.300000 -0.400000  0.500000  1.745329e-02  3.054326e-02   
1        1.0  0.298364 -0.381262  0.496741  1.730938e-02  2.922441e-02   
2        2.0  0.296864 -0.363372  0.493511  1.715057e-02  2.792046e-02   
3        3.0  0.295507 -0.346282  0.490309  1.697824e-02  2.663171e-02   
4        4.0  0.294295 -0.329951  0.487134  1.679370e-02  2.535851e-02   
...      ...       ...       ...       ...           ...           ...   
1196  1196.0 -0.758462  0.270963  0.137718 -3.275286e-07 -1.862932e-07   
1197  1197.0 -0.758536  0.270611  0.137636 -3.337823e-07 -1.855673e-07   
1198  1198.0 -0.758609  0.270259  0.137554 -3.398861e-07 -1.848276e-07   
1199  1199.0 -0.758683  0.269907  0.137472 -3.458416e-07 -1.840743e-07   
1200  1200.0 -0.758756  0.269555  0.137391 -3.516504e-07 -1.833079e-07   

        omega3  
0    -0.038397  
1    -0.037215  
2    -0.036073  
3    -0.034968  
4    -0.033900  
...      

**Your tasks are:**

Numerically implement the nadir pointing control mode and for now just assume that at 
$t_0$
nadir pointing is required, even though the satellite is in the sunlight at this time.

Validate the response by providing the 
$\sigma_{B/N}$
states at 
$t = 15s$, $t = 100s$, $t = 200s$, and $t = 400s$. Note that you must always provide the MRP corresponding to the short rotation.

Submit the following for grading in Coursera:

### Part 1:
Compute the 
$\sigma_{B/N}$
state at 
$t = 15s$

Tolerance: ±0.001

In [10]:
t_measure = 15
sigma_BN = get_state_at_time(data, t=t_measure)[0,1:4]
print(F"sigma_BN(t={t_measure}) = {sigma_BN}")
with open("SCDC-M3-T9-P1.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

sigma_BN(t=15) = [ 0.29108352 -0.1912382   0.45350852]


### Part 2:
Compute the 
$\sigma_{B/N}$
state at 
$t = 100s$

Tolerance: ±0.001

In [11]:
t_measure = 100
sigma_BN = get_state_at_time(data, t=t_measure)[0,1:4]
print(F"sigma_BN(t={t_measure}) = {sigma_BN}")
with open("SCDC-M3-T9-P2.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

sigma_BN(t=100) = [ 0.56621803 -0.13722712  0.15220217]


### Part 3:
Compute the 
$\sigma_{B/N}$
state at 
$t = 200s$

Tolerance: ±0.001

In [12]:
t_measure = 200
sigma_BN = get_state_at_time(data, t=t_measure)[0,1:4]
print(F"sigma_BN(t={t_measure}) = {sigma_BN}")
with open("SCDC-M3-T9-P3.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

sigma_BN(t=200) = [ 0.79607786 -0.45945734 -0.12652816]


### Part 4:
Compute the 
$\sigma_{B/N}$
state at 
$t = 400s$

Tolerance: ±0.001

In [13]:
t_measure = 400
sigma_BN = get_state_at_time(data, t=t_measure)[0,1:4]
print(F"sigma_BN(t={t_measure}) = {sigma_BN}")
with open("SCDC-M3-T9-P4.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

sigma_BN(t=400) = [-0.65299862  0.53453659  0.17454666]


### Programming Assignment: Task 10: GMO Pointing Control (10 points)
Next the GMO pointing attitude mode is created and test. Use the same gains K and P as developed for sun-pointing, and the PD control in Eq. (4). Your tasks are:
 
- Numerically implement the GMO pointing control mode and for now just assume that at $t_0$ nadir pointing is required, even though the satellite is in the sunlight at this time.

- Validate the response by providing the $\sigma_{B/N}$ states at t = 15s, 100s, 200s and 400s. Note that you must always provide the MRP corresponding to the short rotation.

In [14]:
SO.LMO_sat.reset_X()

t_step = 1
t_f = 1200

Xr = lambda t: np.vstack([am.DCM_2_MRP(SO.Get_Comm_Frame_DCM(t)),
                          SO.LMO_sat.R_BN()@SO.Get_Comm_Frame_Inertial_Rate(t,0.01)])

control = lambda x, t: SO.linear_control(x, 
                                         Xr,
                                         t, K, P)
data = SO.orbital_att_RK4int(SO.LMO_sat,
                      control,
                      np.zeros(3),
                      SO.LMO_sat.X(),
                      np.arange(0,t_f+t_step,t_step))
print(data)

fig = pgo.Figure()
sigma = np.array([Xr(t).flatten() for t in np.arange(0,t_f+t_step,t_step)])

fig.add_scatter3d(x=sigma[:,0],
                  y=sigma[:,1],
                  z=sigma[:,2],
                  mode="markers",
                  marker={"size": 1})
fig.add_scatter3d(x=data["sigma1"],
                  y=data["sigma2"],
                  z=data["sigma3"],
                  marker={"size": 1})
fig.show()

           t    sigma1    sigma2    sigma3    omega1    omega2    omega3
0        0.0  0.300000 -0.400000  0.500000  0.017453  0.030543 -0.038397
1        1.0  0.298221 -0.381128  0.496769  0.017444  0.030277 -0.037343
2        2.0  0.296303 -0.362846  0.493621  0.017419  0.029997 -0.036311
3        3.0  0.294265 -0.345129  0.490556  0.017382  0.029705 -0.035302
4        4.0  0.292125 -0.327951  0.487572  0.017331  0.029400 -0.034315
...      ...       ...       ...       ...       ...       ...       ...
1196  1196.0  0.014217 -0.015993  0.380365  0.000011  0.000031  0.000153
1197  1197.0  0.014213 -0.015986  0.380409  0.000011  0.000031  0.000153
1198  1198.0  0.014209 -0.015979  0.380453  0.000011  0.000031  0.000153
1199  1199.0  0.014204 -0.015972  0.380497  0.000011  0.000031  0.000153
1200  1200.0  0.014200 -0.015965  0.380541  0.000011  0.000031  0.000153

[1201 rows x 7 columns]


**Your tasks are:**
Numerically implement the GMO pointing control mode and for now just assume that at 
t = 0 nadir pointing is required, even though the satellite is in the sunlight at this time.

Validate the response by providing the $\sigma_{B/N}$ states at $t = 15s$, $t = 100s$, $t = 200s$, and $t = 400s$. Note that you must always provide the MRP corresponding to the short rotation.

Submit the following for grading in Coursera:



## Part 1:
Compute the $\sigma_{B/N}$ state at $t = 15s$

Tolerance: ±0.001

In [15]:
t_measure = 15
sigma_BN = get_state_at_time(data, t=t_measure)[0,1:4]
print(F"sigma_BN(t={t_measure}) = {sigma_BN}")
with open("SCDC-M3-T10-P1.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

sigma_BN(t=15) = [ 0.26543552 -0.1687908   0.45949195]


## Part 2:
Compute the $\sigma_{B/N}$ state at $t = 100s$

Tolerance: ±0.001

In [16]:
t_measure = 100
sigma_BN = get_state_at_time(data, t=t_measure)[0,1:4]
print(F"sigma_BN(t={t_measure}) = {sigma_BN}")
with open("SCDC-M3-T10-P2.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

sigma_BN(t=100) = [0.15614676 0.22163854 0.34318839]


## Part 3:
Compute the $\sigma_{B/N}$ state at $t = 200s$

Tolerance: ±0.001

In [17]:
t_measure = 200
sigma_BN = get_state_at_time(data, t=t_measure)[0,1:4]
print(F"sigma_BN(t={t_measure}) = {sigma_BN}")
with open("SCDC-M3-T10-P3.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

sigma_BN(t=200) = [0.087284   0.11935138 0.31623424]


## Part 4:
Compute the $\sigma_{B/N}$ state at $t = 400s$

Tolerance: ±0.001

In [18]:
t_measure = 400
sigma_BN = get_state_at_time(data, t=t_measure)[0,1:4]
print(F"sigma_BN(t={t_measure}) = {sigma_BN}")
with open("SCDC-M3-T10-P4.txt","w") as f:
    f.write(" ".join(str(sigma) for sigma in sigma_BN.flatten()))

sigma_BN(t=400) = [ 0.00497732 -0.01648665  0.342438  ]
