# Coursera Spacecraft Dynamics and Control - Kinematics
## Module 4
## Concept Check 3, 4, 5, 6 - Devenport's q-Method, Quest, and OLAE

In [8]:
import numpy as np
import sys

sys.path.append('../')

import attitude_math as am

## Question 6

A spacecraft has two attitude sensors, sensing two unit vectors (directions), $\mathbf{v}^1$ and $\mathbf{v}^2$ with $i=1,2$. Assume the sensors have about the same accuracy. At an instant in time, the two vectors measured by the sensors have the body frame components: 

$\mathbf{B}\,\mathbf{v}^1 = \begin{pmatrix} 0.8273 \\ 0.5541 \\ -0.0920 \end{pmatrix}$

$\mathbf{B}\,\mathbf{v}^2 = \begin{pmatrix} -0.8285 \\ 0.5522 \\ -0.0955 \end{pmatrix}$

At the same time, the four vectors are determined to have inertial frame components:

$\mathbf{N}\,\mathbf{v}^1 = \begin{pmatrix} -0.1517 \\ -0.9669 \\ 0.2050 \end{pmatrix}$

$\mathbf{N}\,\mathbf{v}^2 = \begin{pmatrix} -0.8393 \\ 0.4494 \\ -0.3044 \end{pmatrix}$

Use Devenport's q-Method to determine the estimated attitude $[\mathbf{\bar{B}N}]$. Be sure to normalize all the provided unit vectors. Enter a response with at least 4 significant digits.

In [9]:
v1 = [.8273, .5541, -.0920]
v2 = [-.8285, .5522, -.0955]
n1 = [-.1517, -.9669, .2050]
n2 = [-.8393, .4494, -.3044]
vs = np.vstack((v1,v2))
ns = np.vstack((n1,n2))

print(am.triad_method_estimator(v1, v2, n1, n2))
q = am.q_method_estimator(vs, ns, [1,1])
#print(np.linalg.norm(q))
print(am.quat_2_dcm(q))

[[ 0.41555875 -0.85509088  0.31004921]
 [-0.83393237 -0.49427603 -0.24545471]
 [ 0.36313597 -0.15655922 -0.91848869]]
[[ 0.41593629 -0.85489358  0.31008704]
 [-0.83375671 -0.49463669 -0.24532486]
 [ 0.36310707 -0.15649764 -0.91851061]]


In [10]:
b_bar_n = np.array([[0.969846,-0.200706,-0.138258],[0.17101, 0.96461, -0.200706],[0.173648, 0.17101, 0.969846]]).transpose()
b_bar_n
bn = np.array([[0.963592, -0.223042, -0.147454],[0.187303, 0.956645, -0.223042],[0.190809, 0.187303, 0.963592]]).transpose()
r=b_bar_n@bn.transpose()
print(np.linalg.det(r))
print(r)
q = am.dcm_2_quat(r)
print(np.rad2deg(np.arccos(q[0]))*2)
print(np.rad2deg(np.linalg.norm(am.DCM_2_MRP(r)))*4)

0.9999991558839341
[[ 0.99970013 -0.02019574 -0.01382426]
 [ 0.0199059   0.99958589 -0.02076977]
 [ 0.01423821  0.02048801  0.99968841]]
1.8349476067252135
1.8349868166166081


### Question 5 Check 5
Use the QUEST Algorithm  to determine the estimated attitude 
[𝐵𝑁].  Be sure to normalize all the provided unit vectors. Enter a response with at least 5 significant digits.

In [11]:
CRP = am.quest_method_estimator(vs, ns, [1,1], 2)
print(CRP)
dcm = am.CRP_2_DCM(CRP)
print(am.CRP_2_DCM(CRP).reshape(9).tolist())

[[-31.84928645]
 [ 19.01050463]
 [ -7.5786916 ]]
[0.4159362912691978, -0.8548935784337749, 0.3100870380359689, -0.8337567120720426, -0.4946366939326556, -0.24532485828017808, 0.3631070732993814, -0.156497637579829, -0.9185106111264529]


Testing of my quest method on example

In [12]:
v2s = [[0.8190, -.5282,.2242],[-.3138,-.1584,.9362]]
n2s = [[1, 0, 0],[0,0,1]]
crp = am.quest_method_estimator(v2s, n2s, [1,1], 5)
print(crp)
print(np.array(am.CRP_2_DCM(crp)))


[[-0.12362744]
 [ 0.149115  ]
 [ 0.27392261]]
[[ 0.82514287  0.45928237 -0.32893608]
 [-0.52556132  0.83763943 -0.14881358]
 [ 0.20718237  0.29566855  0.93255326]]


### Question 2 Check 6
Use the OLAE Algorithm to determine the estimated attitude $\mathbf{\bar{B}N}$. Be sure to normalize all the provided unit vectors. Enter a response with at least 5 significant digits.


In [16]:
q = am.OLAE_estimator(vs, ns, [1,1])
print(q)
d = am.CRP_2_DCM(q)
print(d)
print(d.flatten().tolist())

[-31.82302241  18.98792163  -7.57095733]
[[ 0.41621866 -0.85476227  0.31007013]
 [-0.83360793 -0.49490091 -0.2452976 ]
 [ 0.36312512 -0.15637948 -0.9185236 ]]
[0.4162186558929023, -0.8547622734575249, 0.31007013135809935, -0.8336079265803267, -0.4949009125334435, -0.24529759786025912, 0.3631251233791928, -0.15637948282076006, -0.9185235991108545]
