# Coursera Spacecraft Dynamics and Control - Control of Nonlinear Spacecraft Attitude Motion
## Module 2
## Concept Check 1 - Definite Function

In [3]:
import numpy as np
import sys
sys.path.append('../../')

import attitude_math as am

### Question 6
What is the definiteness of the matrix?
$$[K] = \begin{bmatrix}
1.53947 & -0.0422688 & -0.190629 \\
-0.0422688 & 1.4759 & 0.459006 \\
-0.190629 & 0.459006 & 1.48463 \\
\end{bmatrix}$$

In [4]:
K = np.array([
    [1.53947, -0.0422688, -0.190629],
    [-0.0422688, 1.4759, 0.459006],
    [-0.190629, 0.459006, 1.48463],
    ]).transpose()
np.linalg.eig(K)[0]

array([1.99999822, 1.50000363, 0.99999815])

### Question 7
What is the definiteness of the matrix

$$
[K] = \begin{bmatrix}
-0.984331 & -1.10006 & -0.478579 \\
-1.10006 & 1.03255 & 0.338318 \\
-0.478579 & 0.338318 & 1.45178 \\
\end{bmatrix}
$$

In [5]:
K = np.array([
    [-0.984331, -1.10006, -0.478579],
    [-1.10006, 1.03255, 0.338318],
    [-0.478579, 0.338318, 1.45178],
    ])

np.linalg.eig(K)[0]

array([-1.49999901,  1.99999849,  0.99999952])

### Question 8
What is the definiteness of the matrix

$$
[K] = \begin{bmatrix}
-2.0353 & 0.296916 & -0.365128 \\
0.296916 & -1.10369 & -0.074481 \\
-0.365128 & -0.074481 & -2.86101 \\
\end{bmatrix}
$$


In [6]:
K = np.array([[-2.0353, 0.296916, -0.365128],
              [0.296916, -1.10369, -0.074481],
              [-0.365128, -0.074481, -2.86101]])

np.linalg.eig(K)[0]

array([-3.00000223, -1.99999849, -0.99999928])