# Coursera Spacecraft Dynamics and Control - Kinematics
## Module 3
## Concept Check 11, 12 - CRP Addition

In [9]:
import numpy as np
import sys
sys.path.append('../')

import attitude_math as am

### Problem 1
Given the CRP attitude description $\mathbf{q}_{B/N} = (0.1, 0.2, 0.3)$, what is the equivalent DCM value?

In [10]:
dcm = am.CRP_2_DCM([0.1, 0.2, 0.3])
dcm.reshape(9).tolist()

[0.7719298245614035,
 array([0.56140351]),
 array([-0.29824561]),
 array([-0.49122807]),
 0.8245614035087718,
 array([0.28070175]),
 array([0.40350877]),
 array([-0.07017544]),
 0.9122807017543859]

### Problem 2
Given the DCM 

$[BN] = 
\begin{bmatrix}
0.333333 & -0.666667 & 0.666667 \\
0.871795 & 0.487179 & 0.0512821 \\
-0.358974 & 0.564103 & 0.74359 \\
\end{bmatrix}$, what is the equivalent CRP set?


In [11]:
dcm = np.array([[0.333333, -0.666667, 0.666667],
                [0.871795, 0.487179, 0.0512821],
                [-0.358974, 0.564103, 0.743597]])
am.quat_2_CRP(am.dcm_2_quat(dcm)).tolist()

[[-0.1999928238892705], [-0.399995885489166], [-0.6000018719923811]]

### Question 4

Let $\mathbf{q}_{F/N} = (0.1, 0.2, 0.3)$ and $\mathbf{q}_{B/N} = (-0.3, 0.3, 0.1)$. What is the attitude of $\mathbf{B}$ relative to $\mathbf{F}$ in terms of CRPs?

In [12]:
am.CRP_add([-0.1, -0.2, -0.3],[-0.3, 0.3, 0.1])

array([-0.31132075,  0.18867925, -0.27358491])