# Coursera Spacecraft Dynamics and Control - Kinematics
## Module 4
## Concept Check 2 - TRIAD Method

In [8]:
import numpy as np
import sys

sys.path.append('../')

import attitude_math as am

### Question 1

A spacecraft has two attitude sensors, sensing two unit vectors (directions), $\hat{v}_1$ and $\hat{v}_2$ with $i=1,2$. We know the first sensor ($i=1$) is more accurate than the second sensor. At an instant in time, the two vectors measured by the sensors have the body frame components: 

$^\mathbf{B}\hat{v}_1 = \begin{pmatrix} 0.8273 \ 0.5541 \ -0.0920 \end{pmatrix}$ and $^\mathbf{B}\hat{v}_2 = \begin{pmatrix} -0.8285 \ 0.5522 \ -0.0955 \end{pmatrix}$.

At the same time, the four vectors are determined to have inertial frame components:

$^\mathbf{N}\hat{v}_1 = \begin{pmatrix} -0.1517 \ -0.9669 \ 0.2050 \end{pmatrix}$ and $^\mathbf{N}\hat{v}_2 = \begin{pmatrix} -0.8393 \ 0.4494 \ -0.3044 \end{pmatrix}$.

Use the Triad Method to determine the estimated attitude $[\bar{\mathbf{B}}N]$. Be sure to normalize all the provided unit vectors. Enter a response with at least 5 significant digits.

In [9]:
v1 = [.8273, .5541, -.0920]
v2 = [-.8285, .5522, -.0955]
n1 = [-.1517, -.9669, .2050]
n2 = [-.8393, .4494, -.3044]

am.triad_method(v1, v2, n1, n2).reshape(9).tolist()

[0.4155587495161771,
 -0.8550908811348732,
 0.31004920690196414,
 -0.833932366309469,
 -0.49427603231729206,
 -0.24545470518644497,
 0.3631359719472038,
 -0.15655921843398826,
 -0.9184886918200454]

### Question 2

Assume the estimated attitude is given by

$\bar{\mathbf{B}N} = \begin{bmatrix} 0.969846 & 0.17101 & 0.173648 \\ -0.200706 & 0.96461 & 0.17101 \\ -0.138258 & -0.200706 & 0.969846 \end{bmatrix}$

and the true attitude is given by

$\mathbf{BN} = \begin{bmatrix} 0.963592 & 0.187303 & 0.190809 \\ -0.223042 & 0.956645 & 0.187303 \\ -0.147454 & -0.223042 & 0.963592 \end{bmatrix} $

Express the estimation error in terms of a principal rotation angle in units of degrees.

In [33]:
b_bar_n = np.array([[0.969846,-0.200706,-0.138258],[0.17101, 0.96461, -0.200706],[0.173648, 0.17101, 0.969846]]).transpose()
b_bar_n
bn = np.array([[0.963592, -0.223042, -0.147454],[0.187303, 0.956645, -0.223042],[0.190809, 0.187303, 0.963592]]).transpose()
r=b_bar_n@bn.transpose()
print(np.linalg.det(r))
print(r)
q = am.dcm_2_quat(r)
print(np.rad2deg(np.arccos(q[0]))*2)
print(np.rad2deg(np.linalg.norm(am.DCM_2_MRP(r)))*4)

0.9999991558839341
[[ 0.99970013 -0.02019574 -0.01382426]
 [ 0.0199059   0.99958589 -0.02076977]
 [ 0.01423821  0.02048801  0.99968841]]
1.8349476067252135
1.8349868166166081
