# Coursera Spacecraft Dynamics and Control - Kinetics
## Module 1


In [5]:
import numpy as np

## Concept Check 2 - Kinetic Energy

### Question 2
A cloud contains four particles with masses $m_1 = m_2 = 1$ kg and $m_3 = m_4 = 2$ kg. The position vector of each particle is $\mathbf{R}_1 = (1, -1, 2)$ m, $\mathbf{R}_2 = (-1, -3, 2)$ m, $\mathbf{R}_3 = (2, -1, -1)$ m, $\mathbf{R}_4 = (3, -1, -2)$ m and their respective velocity vectors are $\dot{\mathbf{R}_1} = (2, 1, 1)$ m/s, $\dot{\mathbf{R}_2} = (0, -1, 1)$ m/s, $\dot{\mathbf{R}_3} = (3, 2, -1)$ m/s, $\dot{\mathbf{R}_4} = (0, 0, 1)$ m/s.

How much of the total cloud kinetic energy is translational kinetic energy and how much is rotation and deformation energy (measured in Joules)?

In [42]:
rs = np.array([[1,-1,2],
      [-1,-3,2],
      [2,-1,-1],
      [3,-1,-2]])
r_dots = np.array([[2,1,1],
          [0,-1,1],
          [3,2,-1],
          [0,0,1]])
ms = np.array([1, 1, 2, 2])
M = np.sum(ms)

rc = ms@rs/M
rc_dot = ms@r_dots/np.sum(ms)
print(f"Center of Mass: {rc} | Velocity of COM: {rc_dot}")

T_trans = 1/2*M*np.inner(rc_dot,rc_dot)
R_dots = r_dots-rc_dot
print(r_dots,"\n",R_dots)
T_deform = 1/2*np.trace(ms*(R_dots@R_dots.transpose()))
T_tot = 1/2*np.trace(ms*(r_dots@r_dots.transpose()))
print(f"Translational KE: {T_trans} | Deformational KE: {T_deform} | Total KE: {T_tot}")

Center of Mass: [ 1.66666667 -1.33333333 -0.33333333] | Velocity of COM: [1.33333333 0.66666667 0.33333333]
[[ 2  1  1]
 [ 0 -1  1]
 [ 3  2 -1]
 [ 0  0  1]] 
 [[ 0.66666667  0.33333333  0.66666667]
 [-1.33333333 -1.66666667  0.66666667]
 [ 1.66666667  1.33333333 -1.33333333]
 [-1.33333333 -0.66666667  0.66666667]]
Translational KE: 7.0 | Deformational KE: 12.0 | Total KE: 19.0


A cloud contains four particles with masses $m_1 = m_2 = 1$ kg and $m_3 = m_4 = 2$ kg. The respective velocity vectors are:

$\mathbf{R}_1 = \begin{pmatrix} 2 \\ 1 \\ 1 \end{pmatrix}$ m/s

$\mathbf{R}_2 = \begin{pmatrix} 0 \\ -1 \\ 1 \end{pmatrix}$ m/s

$\mathbf{R}_3 = \begin{pmatrix} 3 \\ 2 \\ -1 \end{pmatrix}$ m/s

$\mathbf{R}_4 = \begin{pmatrix} 0 \\ 0 \\ 1 \end{pmatrix}$ m/s

What is the linear momentum of this system?

In [55]:
R_dots = np.array([[2, 1, 1],
          [0, -1, 1],
          [3, 2, -1],
          [0, 0, 1],])
m = np.array([1, 1, 2, 2])
m@R_dots

## Concept Check 4 - Angular Momentum

## Problem 1
A cloud contains four particles with masses 
Given that $m_1 = m_2 = 1$ and $m_3 = m_4 = 2$, the position vector of each particle is:

$R_1 = \begin{pmatrix} 1 \\ -1 \\ 2 \end{pmatrix}$,
$R_2 = \begin{pmatrix} -1 \\ -3 \\ 2 \end{pmatrix}$,
$R_3 = \begin{pmatrix} 2 \\ -1 \\ -1 \end{pmatrix}$,
$R_4 = \begin{pmatrix} 3 \\ -1 \\ -2 \end{pmatrix}$.

Their respective velocity vectors are:

$R_1' = \begin{pmatrix} 2 \\ 1 \\ 1 \end{pmatrix}$,
$R_2' = \begin{pmatrix} 0 \\ -1 \\ 1 \end{pmatrix}$,
$R_3' = \begin{pmatrix} 3 \\ 2 \\ -1 \end{pmatrix}$,
$R_4' = \begin{pmatrix} 0 \\ 0 \\ 1 \end{pmatrix}$.

What is the cloud angular momentum vector about the origin and about the center of mass?

In [75]:
import numpy as np

R1 = np.array([1, -1, 2])
R2 = np.array([-1, -3, 2])
R3 = np.array([2, -1, -1])
R4 = np.array([3, -1, -2])

R1_prime = np.array([2, 1, 1])
R2_prime = np.array([0, -1, 1])
R3_prime = np.array([3, 2, -1])
R4_prime = np.array([0, 0, 1])

Rs = np.array([R1, R2, R3, R4])
R_primes = np.array([R1_prime, R2_prime, R3_prime, R4_prime])

Rc = ms@rs/M
Rc_dot = ms@r_dots/np.sum(m)
print(f"COM: {Rc} COM Velocity: {Rc_dot}")

m=[1, 1, 2, 2]
H0 = m@np.cross(Rs,R_primes)
HC = m@np.cross(Rs-Rc,R_primes-Rc_dot)
print(F"H0:{H0}\nHC:{HC}")


COM: [ 1.66666667 -1.33333333 -0.33333333] COM Velocity: [1.33333333 0.66666667 0.33333333]
H0:[ 0 -4 18]
HC:[1.33333333 2.         0.66666667]


In [71]:
np.cross(Rs,R_primes)
#np.cross([1,-1,2],[2,1,1])

array([[-3,  3,  3],
       [-1,  1,  1],
       [ 3, -1,  7],
       [-1, -3,  0]])